[custom.all.idris2-wai]
type = "local"
path = "."
ipkg = "idris2-wai.ipkg"

[custom.all.idris2-http-types]
type   = "github"
url    = "https://github.com/rafaelRiv/idris2-http-types"
commit = "a4e5f1b90c20b2cce56eab0779a9af3217d4e45a"
ipkg   = "idris2-http-types.ipkg"
