[custom.all.idris2-wai]
type = "local"
path = "."
ipkg = "idris2-way.ipkg"

[custom.nightly-250221.idris2-http-types]
type   = "github"
url    = "https://github.com/rafaelRiv/idris2-http-types"
commit = "9cecf0b9eefa3fee0bd3ebc91f188cfec4bedd1e"
ipkg   = "idris2-http-types.ipkg"
